spring:
  application:
    name: student-teacher-marks-data-service
  datasource:
    url: jdbc:mysql://localhost:3306/grade_management_system
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update      
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

server:
  port: 8084
